Repository Open-EO/openeo-processes, pull requests merged in 2020-07, with the labels that each got.

#162 `mean`: add process graph, clarify null arrays
  CHANGELOG.md
  mean.json
Labels: documentation

#167 #159: `linear_scale_range`: Clarify that the process implicitly clips the values.
  CHANGELOG.md
  linear_scale_range.json
Labels: bug, documentation

#166 Fixes #165: clarify kernel orientation
  CHANGELOG.md
  apply_kernel.json
Labels: documentation

#163 #154 add apply_neighbourhood
  CHANGELOG.md
  apply_kernel.json
  apply_neighborhood.json
  meta/subtype-schemas.json
  tests/processes.test.js
Labels: new process

#182 Consistent and intuitive description for returned data cubes #149
  CHANGELOG.md
  add_dimension.json
  aggregate_temporal.json
  aggregate_temporal_period.json
  anomaly.json
  apply.json
  apply_dimension.json
  apply_kernel.json
  apply_neighborhood.json
  climatological_normal.json
  create_raster_cube.json
  drop_dimension.json
  filter_bands.json
  filter_bbox.json
  filter_labels.json
  filter_spatial.json
  filter_temporal.json
  load_collection.json
  mask.json
  mask_polygon.json
  merge_cubes.json
  ndvi.json
  reduce_dimension.json
  reduce_dimension_binary.json
  rename_dimension.json
  rename_labels.json
  resample_cube_spatial.json
  resample_cube_temporal.json
  resample_spatial.json
  run_udf.json
  run_udf_externally.json
  trim_cube.json
Labels: documentation
