Repository Open-EO/openeo-processes, pull requests merged in 2023-03, with the labels that each got.

#403 Add vector_reproject
  CHANGELOG.md
  aggregate_spatial.json
  aggregate_temporal.json
  aggregate_temporal_period.json
  filter_temporal.json
  proposals/aggregate_spatial_window.json
  proposals/reduce_spatial.json
  proposals/resample_cube_temporal.json
  proposals/vector_reproject.json
  resample_cube_spatial.json
  resample_spatial.json
  tests/.words
Labels: new process, vector

#421 `array_modify`: Change the default value for `length` from `1` to `0`.
  CHANGELOG.md
  proposals/array_modify.json
Labels: breaking

#298 Add apply_polygon #287
  CHANGELOG.md
  mask_polygon.json
  proposals/apply_polygon.json
Labels: new process, vector

#422 Removed support for arrays and objects from comparisons. #208
  CHANGELOG.md
  array_contains.json
  eq.json
  gt.json
  gte.json
  lt.json
  lte.json
  neq.json
Labels: breaking

#419 Change proposal status of some processes #301
  CHANGELOG.md
  array_append.json
  array_concat.json
  array_create.json
  array_interpolate_linear.json
  resample_cube_temporal.json
Labels: waiting

#297 quantiles: Deprecate q in favor of probabilities #293
  CHANGELOG.md
  quantiles.json
Labels: breaking, must-have

#412 Streamline GeoJSON import #346
  CHANGELOG.md
  aggregate_spatial.json
  filter_spatial.json
  load_collection.json
  mask_polygon.json
  meta/subtype-schemas.json
  proposals/filter_vector.json
  proposals/vector_buffer.json
  proposals/vector_to_random_points.json
  proposals/vector_to_regular_points.json
  tests/.words
Labels: vector, discussion needed

#424 Improve summary of order process
  order.json
  rearrange.json
Labels: documentation
